apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-board
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: kanban-board
  template:
    metadata:
      labels:
        app: kanban-board
    spec:
      containers:
        - name: kanban-board
          image: ahmedibrahimlab/kanban-board  # Replace with your Docker image
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: DATABASE_URL
              value: "mysql://root:password@db:3306/kanban_ms"  # Adjust as needed
